
PUC_TYPES = ["Catholic Univ Chile",
             "Catholic Univ Clin Hosp, Santiago",
             "Catholic Univ Santiago, Santiago",
             "Catholic Univ, Sch Med, Santiago, Chile",
             "Catholic Univ, Sch Psychol, Santiago",
             "Catholic University of Chile",
             "Pontificia Univ Catolica",
             "Catholic University, Santiago, Chile",
             "CLAPES-Universidad CatolicaSantiago, Chile",
             "Hosp Clin Univ Catolica, Div Neonatol, Santiago",
             "Hospital Clinico Universidad Catolica, Santiago",
             "P Univ Catolic Chile, Dept Urol, Santiago, Chile",
             "P Univ Catolica, Div Pediat, Santiago 8330024, RM, Chile",
             "P Univ Catolica, Fac Ciencias Biol, Dept Genet Mol & Microbiol, Santiago",
             "P. Catholic University of Chile",
             "P. Univ. Catlica de Chile, Chile",
             "P. Universidad Católica de Chile",
             "Pont. Univ. Católica, IMC, Santiago",
             "Pont. Univ. Católica, Santiago",
             "Pontficia Univ Cathlica Chile",
             "Ponti fi cia Univ Catol Chile",
             "Pontif Cathol Univ Chile",
             "Pontif Univ Catol Chile",
             "Pontif Univ Catolica, Fac Med, Dept Pediat, Santiago",
             "Pontif Univ Catholic Chile",
             "Pontific Catholic Univ Chile",
             "Pontific Catholic University, Santiago",
             "Pontifica Univ Catolica Chile",
             "Inst Filosofia Univ Catolica Chile",
             "Pontifica Universidad Catolica, Santiago",
             "Pontifical Cathol Univ Chile",
             "Pontifical Catholic Univ Chile",
             "Pontifical Catholic Univ, Sch Vet Med, Santiago",
             "Pontifical Catholic Univ, Sch Vet Med, Chile",
             "Pontifical Catholic University of Chile",
             "Pontifical Catholic University, Santiago",
             "Pontifical Catolic Univ Chile",
             "Pontifical Univ Catholic Chile",
             "Pontifical Univ Chile",
             "Pontifical University Catholic of Chile",
             "Pontificia Catholic Univ, Dept Pathol, Santiago, Chile",
             "Pontificia Catholic University, Santiago",
             "Pontificia Catholic UniversitySantiago",
             "Pontificia Catholica Univ Chile",
             "Pontificia Catolica Univ Chile",
             "Pontificia Uni Versidad Católica de Chile",
             "Pontificia Univ Caolica Chile",
             "Pontificia Univ Caólica Chile",
             "Pontificia Univ Catal Chile",
             "Pontificia Univ Catalica Chile",
             "Pontificia Univ Catholic Chile, Dept Radiol, Santiago, Chile",
             "Pontificia Univ Catifil Chile",
             "Pontificia Univ Catifilica Chile",
             "Pontificia Univ Catiolica Chile",
             "Pontificia Univ Catlica Chile",
             "Pontificia Univ Cato Chile",
             "Pontificia Univ Catoica Chile",
             "Pontificia Univ Catoical Chile",
             "Pontificia Univ CatoIica Chile",
             "Pontificia Univ Catol Chile",
             "Pontificia Univ Catolcia Chile",
             "Pontificia Univ Catolic Chile",
             "Pontificia Univ Catolica Chile",
             "Pontificia Univ Catolica Chile Anid",
             "Pontificia Univ CatOlica Chile",
             "Pontificia Univ Católica Chile",
             "Pontifi Cia Universidad Catolica De Chile",
             "Pontificia Univ Catolica Chil",
             "Pontificia Univ Católica de Chile",
             "Pontificia Univ Catolica, Anat Patol, Santiago",
             "Pontificia Univ Católica, Anat Patol, Santiago",
             "Pontificia Univ Catolica, Artes, Santiago",
             "Pontificia Univ Católica, Artes, Santiago",
             "Pontificia Univ Católica, Clin San Carlos Apoquindo, Santiago",
             "Pontificia Univ Catolica, Clin San Carlos Apoquindo, Santiago",
             "Pontificia Univ Catolica, Escuela Psicol, Santiago",
             "Pontificia Univ Católica, Escuela Psicol, Santiago",
             "Pontificia Univ Catolica, Escuela Psicol, Santiago",
             "Pontificia Univ Católica, Escuela Psicol, Santiago",
             "Pontificia Univ Catolica, Fac Ciencias Biol, Ctr Envejecimiento & Regenerac CARE UC, Santiago",
             "Pontificia Univ Católica, Fac Ciencias Biol, Ctr Envejecimiento & Regenerac CARE UC, Santiago",
             "Pontificia Univ Catolica, Fac Derecho, Santiago",
             "Pontificia Univ Católica, Fac Derecho, Santiago",
             "Pontificia Univ Catolica, Fac Educ, Santiago",
             "Pontificia Univ Católica, Fac Educ, Santiago",
             "Pontificia Univ Catolica, Pedag Gen Basica, Santiago",
             "Pontificia Univ Catolica, Sch Management, Ave Vicuna Mackenna, Santiago",
             "Pontificia Univ Catolicica Chile, Santiago",
             "Pontificia Univ Catolico Chile",
             "Pontificia Univ Catololica Chile",
             "Pontificia Univ Chile",
             "Pontificia Univ Chile, Dept Neurol, Santiago, Chile",
             "Pontificia Univ Chile, DILAB Sch Engn, Santiago, Chile",
             "Pontificia Univ Chile, Sch Engn, Santiago, Chile",
             "Pontificia Univ, Catol Chile",
             "Pontificia Univ, Dept Construct Engn & Management, Chile",
             "Pontificia Univ, Santiago",
             "Pontificia Univ. Catolica de Chile",
             "Pontificia Univ. Católica de Chile",
             "Pontifícia Univ. Católica, Chile",
             "Pontifícia Univ. Católica, IMC, Santiago",
             "Pont Univ Catolica, IMC, Santiago, Chile",
             "Pontificia Univ Catolica, IMC, Santiago, Chile",
             "Pontificia Univerdad Catolica de Chile",
             "Pontificia Univerisdad Católica de Chile, Santiago, Chile",
             "Pontificia Univers Catol Chile",
             "Pontificia Universidad Caatólica de Chile",
             "Pontificia Universidad Caólica de Chile",
             "Pontificia Universidad Cat lica de Chile",
             "Pontificia Universidad Cat&#x00F3;lica de Chile",
             "Pontificia Universidad CatÃ³lica de Chile",
             "Pontificia Universidad Cat\'olica de Chile, Santiago, Chile",
             "Pontificia Universidad Cat_olica de Chile",
             "Pontificia Universidad Cat´olica de Chile",
             "Pontificia Universidad Cat olica de Chile",
             "Pontificia Universidad Catalica de Chile",
             "Pontificia Universidad Catholica de Chile",
             "Pontificia Universidad Catlica de Chile",
             "Pontificia Universidad Cató Lica de Chile",
             "Pontificia Universidad Cató lica de Chile",
             "Pontificia Universidad Católica (UC), Santiago",
             "Pontificia Universidad Católica Chile",
             "Pontificia Universidad Católica de Chil",
             "Pontificia Universidad Catolica de Chile",
             "Pontificia Universidad Catolica De Chile",
             "Pontificia universidad catolica de chile",
             "Pontificia Universidad Catolicá de Chile",
             "Pontificia Universidad Católica de Chile",
             "Pontificia Universidad Católica De Chile",
             "Pontificia Universidad Católica de chile",
             "Pontificia Universidad católica De Chile",
             "Pontificia Universidad catóLica de Chile",
             "Pontificia Universidad católica de chile",
             "Pontificia Universidad Católi-ca de Chile",
             "Pontificia Universidad Catòlica de Chile",
             "PONTIFICIA UNIVERSIDAD CATÓLICA DE CHILE, Chile",
             "Pontificia Universidad CatÓlica de Chile, Santiago de Chile",
             "Pontificia Universidad Catolica de Chile.",
             "Pontificia Universidad Católica de Chile",
             "Pontificia Universidad Catolica de, Chile",
             "Pontificia Universidad Católica de, Santiago",
             "Pontificia Universidad Catolica of Chile",
             "Pontificia Universidad Católica of Chile",
             "Pontificia Universidad Católica Santiago de Chile",
             "Pontificia Universidad Catolicade Chile",
             "Pontificia Universidad Católic, Chile",
             "Pontificia Univ Catolica Santiago",
             "Pontificia Univ Católica Santiago",
             "Pontificia Universidad Católica (Chile)",
             "Pontificia Universidad Catolica (Chile)",
             "Pontificia Universidad Católica, Av. Vicuña Mackenna 4860",
             "Pontificia Universidad Católica, Chile",
             "Pontificia Universidad Catolica, Chile",
             "Pontificia Universidad Católica, de Chile",
             "Pontificia Universidad Catolica, de Chile",
             "Pontificia Universidad Católica, Departamento de Endocrinología, Escuela de Medicina, Santiago",
             "Pontificia Universidad Católica, Department of Medicine, Gastroenterology, Marcoleta 367",
             "Pontificia Universidad Católica, El Comendador 1916",
             "Pontificia Universidad Catolica, Electrical Engineering Department, Avenida Vicuña Mackenna 4860",
             "Pontificia Universidad Católica, Instituto de Astrofisica, Chile",
             "Pontificia Universidad Católica, Production Management Centre, Vicuña Mackena 4860, Santiago",
             "Pontificia Universidad Católica, RegiÃn Metropolitana",
             "Pontificia Universidad Católica., Santiago",
             "Pontificia Universidad Catolica, Santiago",
             "Pontificia Universidad Católica, Santiago",
             "Pontifícia Universidad Catolica, Santiago",
             "Pontificia Universidad Católica, San Joaquín, 7820436, Chile",
             "Pontificia Universidad Católica, Vicuña Mackenna 4860",
             "PONTIFICIA UNIVERSIDAD CATQLICA DE CHILE",
             "Pontificia Universidad de Católica de Chile",
             "Pontificia Universidad de Chile",
             "Pontificia Universidad, Catolica de Chile",
             "Pontificia Universidad, Católica de Chile",
             "Pontificia Universidad, Católica, Chile",
             "Pontificia Universidade Católica do Chile",
             "Pontifícia Universidade Católica do Chile, Santiago",
             "Pontifícia Universidade Católica, Santiago",
             "Pontificia Universiddad Católica de Chile",
             "Pontificia University Católica de Chile",
             "Pontificia Univesidad Catolica Chile",
             "Pontificia Univesidad Catolica de Chile",
             "Pontificia Univesidad Católica de Chile",
             "Pontificia, Universidad Católica de Chile",
             "PUC Chile",
             "Puc Chile",
             "PUC, Chile",
             "Puc, Chile",
             "PUC, Fac Med, Div Anestesiol, Santiago",
             "PUC, Inst Math & Computat Engn, Santiago",
             "PUC, Santiago",
             "PUC Santiago",
             "PUC-Chile",
             "Univ Catholica Chile",
             "Univ Catholique Pontificale Chili",
             "Univ Catol Chile",
             "Univ Catholic Chile",
             "Univ Catolica Chile",
             "Univ Catolica, Hist, Santiago, Chile",
             "Univ Catolica, Santiago",
             "Univ Pontificia Catolica Chile",
             "Universidad Catlica de Chile",
             "Universidad Catoilica De Chile",
             "Universidad Catolica de Chile",
             "Universidad Católica de Chile",
             "Universidad CatÓlica de Chile",
             "Universidad Católica de, Chile",
             "Universidad Católica, Chile",
             "Universidad Catolica, Santiago",
             "Universidad Católica, Santiago",
             "Universidad Católicade Chile",
             "Universidad Pontificia Católica de Chile",
             "Universidade Católica, Chile",
             "Universidad Catoílica de Chile",
             "Universidade Católica, Santiago",
             "Pontificia Univ Catol, Santiago",
             "Pontificia Univ Catolica, Lab Microbiol Red Salud UC CHRISTUS, Santiago",
             "Pontificia Universidad Católìca de Chile",
             "Pontificia Univ Catolica, Dept Publ Hlth, Santiago, Chile",
             "Pontificia Univ Catolica, Vicuna Mackenna 4860, Santiago, Chile",
             "Pontificia Univ Catolica, Sch Med, Dept Gastroenterol, Santiago, Chile",
             "Pontificia Univ Catolica, Escuela Med, Ctr Invest Med, Santiago, Chile",
             "Pontificia Univ Catolica, Dept Ind & Syst Engn, Santiago, Chile",
             "Pontificia Univ Catolica UC Chile",
             "Pontificia Univ Catholic Chile",
             "Pontificia Univ Catalholica Chile",
             "Pontificia Univ Catlolica Chile",
             "Pontificia Univ Catoolica Chile",
             "Catholic Univ, Div Neonatol, Santiago, Chile",
             "PUC, Dept Comp Sci, Santiago, Chile",
             "Univ Pontif Catolica Chile",
             "Catholic Univ, Sch Med, Dept Cardiol, Santiago, Chile",
             "Catholic Univ, Sch Med, Dept Pediat, Santiago, Chile",
             "Catholic Univ Sch Med, Dept Cardiol, Santiago, Chile",
             "Catholic Univ, Fac Med, Santiago, Chile",
             "Catholic Univ, Dept Cardiol, Sch Med, Santiago, Chile",
             "Pontifical Catholic Univ, Div Neonatol, Sch Med, Santiago, Chile",
             "Catholic Univ, Dept Pediat, Santiago, Chile",
             "P Catolica Univ Chile",
             "P Univ Catholic Chile",
             "Pontificia Univ Cat olica Chile",
             "Pontificia Univ Cat lica Chile",
             "PUC, Dept Fisiol, Santiago, Chile",
             "Univ Catolica de Chile",
             "Pontif Cathol Univ, Santiago, Chile",
             "Pontif Cathol Univ, Respiratory Dis Dept, Santiago, Chile",
             "Pontificia Univ Catolica, Fac Ciencias Biol, Dept Ecol, Santiago 8331150, Chile",
             "Pontifical Catolica Univ Chile",
             "Pontificia Universidad Católica De, Chile",
             "Pontifical Catholic Univ. of Chile",
             "Pontificia Universidad Cat ´Olica de Chile",
             "P. Universidad Catótica de Chile",
             "Pontificia Catholic University, Chile",
             "Pontificia Universidad Catálica de Chile",
             "Pontificia Universi-dad Católica de Chile",
             "Pontífica Universidade Católica do Chile",
             "Pontificia Universidad Catœlica de Chile",
             "Pontificia Universidad Cat Olica de Chile",
             "Pontificia Universidad Cató de Chile",
             "Pontificia Univertsidad Católica de Chile",
             "Pontificia Universidad Catóalica de Chile",
             "P. Universidad Catoilica de Chile",
             "Pontifícia Universidade Católica Do Chile",
             "Pontificia U niversidad C atólica d e C hile",
             "Facultad de Derecho de la Pontificia Universidad Católica (Chile)",
             "Pontifica Universidad Cathólica de Chile",
             "Pontifical Catholic University, Chile",
             "PontificalCatholic, Chile",
             "Pontificia Universidad Católica de Santiago, Chile",
             "Pontificia U. Católica de Chile",
             "Pontifica Universidad Catórilica de Chile",
             "Pontificia Universidad Cat0lica de Chile",
             "Pontificia Universidad Católica (UC), Chile; UC",
             "Université Pontificale Catholique du Chili",
             "Pontificia Universidad Cat\' olica de Chile, Santiago, 4860, Chile",
             "Pontificia Universidad Cátolica de Chile",
             "Pontifícia Univ. Católica de Chile",
             "Pontificia Universidad Catolica de, Santiago, Chile",
             "Pontificia Universidade Católica de Chile",
             "Pontificia Universidad de Santiago de Chile",
             "PUC and IMFD, Vicuña Mackenna 4860",
             "Pontificia, Universidad Católica, Vicuña Mackenna 4860",
             "FADEU, UC, Chile",
             "Universidad Católica, Imfd, Chile",
             "PONTIFICIA UNIVERSIDAD CATÓLICA DE CHILE",
             "PONTIFICIA UNIVERSIDAD CATÓLICA de CHILE",
             "UNIVERSIDAD CATÓLICA DE CHILE, Chile",
             "UC, Chile",
             "Pontificia Universidad Católica (UC), Santiago, Chile",
             "CAPES-UC, Santiago, Chile",
             "Pontifical Catholic University, Institute of Urban Studies, Santiago, Chile",
             "Universidad Católica, Chief of Adult's Infectious Disease Unit, Hospital Dr. Sótero del Río, Chile",
             "Pontificia Universidad Católica, Departamento de Sociología",
             "Pontificia Universidad Católica and Imfd, Vicuña Mackenna 4860",
             "Pontificia Univ Catolica, Ind & Syst Engn Dept, Santiago, Chile",
             "Pontificia Univ Catolica, Inst Profes Fdn Duoc UC, Vina Del Mar, Chile",
             "Pontificia Univ Catolica, Sch Engn, Santiago, Chile",
             "Pontificia Univ Catolica, Dept Ingn Ind & Sistemas, Santiago, Chile",
             "Univ Catolica OCUC, Observ Cities, Geog, Santiago, Chile",
             "Pontificia Univ Catl Chile",
             "Pontificia Univ Catolica, Inst Polit Sci, Santiago, Chile",
             "Pontificia Univ Catolica, Dept Ingn Mecan & Metalurg, Santiago, Chile",
             "Pontificia Univ Catolica, Fac Med, Dept Nefrol, Santiago, Chile",
             "Pontificia Univ Catolice Chile",
             "Pontificia Univ Catolica, Dept Elect Engn, Santiago, Chile",
             "Pontificia Univ Catolica, Fac Ciencias Biol, Santiago, Chile",
             "Pontificia Univ Cathol Chile",
             "Pontificia Univ Catolica, Psychol Fac, Santiago, Chile",
             "Pontificia Univ Catolica, Dept Geotech & Struct Engn, Santiago",
             "Pontificia Univ Catol, Sch Anthropol, Fac Social Sci, Santiago, Chile",
             "Pontificia Univ Santiago de Chile",
             "Pontificia Univ Catohca Chile",
             "Catholic Univ, Minist Hlth & Pontificia, Santiago, Chile",
             "Pontificia Univ Catolica, Fac Ingn, Dept Ingn Quim & Bioproc, Santiago",
             "Pontificia Univ Catolica, Fac Matemat, Vicuna Mackenna 4860, Santiago",
             "Pontificia Univ Catolicade Chile",
             "PUC, Millennium Inst Astrophys, Santiago",
             "PUC, Dept Ecol, Santiago",
             "Pontificia Univ Cattolica De Chile",
             "Pontif Univ Catolica, Fac Med, Santiago",
             "Pontificia Univ Catolica, Fac Med, Dept Salud Publ, Santiago, Chile",
             "Pontificia Univ Catolica, Fac Ciencias Salud, Carrera Nutr & Dietet, Vicuna Mackenna 4860, Santiago, Chile",
             "Univ Catolica, Fac Sociol, Escuela Sociol, Santiago, Chile",
             "Pontificia Univ Catolica, Inst Sociol, Santiago, Chile",
             "Pontificia Univ Catolica, Fac Med, Dept Publ Hlth, Santiago, Chile",
             "Pontificia Univ Catolica, Sch Med, Ctr Evidencia UC, Santiago, Chile",
             "Pontificia Univ Catolica, Econ, Santiago, Chile",
             "Pontificia Univ Catolica, Dept Ind & Syst Engn, Av Vicuna Mackenna 4860",
             "Univ Catolica, Mph, Santiago, Chile",
             "Ponti fi cia Univ Caol Chile",
             "Pontificia Univ Catolica, Fac Agron & Ingn Forestal, Santiago, Chile",
             "Univ Catolica, Escuela Antropol, Archaeol, Santiago, Chile",
             "Pontificia Univ Catolica, Escuela Antropol, Santiago, Chile",
             "Pontificia Univ Catol, Fac Ciencias Biol, Ctr Envejecimiento & Regenerac CARE UC, Santiago, Chile",
             "Pontificia Univ Catolica, Ctr Justicia & Soc, Santiago, Chile",
             "Pontificia Univ Catolica, Inst Math & Computat Engn, Santiago, Chile",
             "Pontificia Univ Catolica, Civil Procedure, Santiago, Chile",
             "Pontificia Univ Catolica, Sch Psychol, Santiago, Chile",
             "Pontificia Univ Catolica, Inst Geog, Santiago, Chile",
             "Pontificia Univ Catolica, Dept Ingn Estruct & Geotecn, Santiago, Chile",
             "Pontificia Univ Catolica, Sociol, Santiago, Chile",
             "Pontificia Univ Catolica UC, Inst Ciencia Polit, Santiago, Chile",
             "Pontificia Univ Catolica, Fac Med, Psychiat Dept, Eating Disorders Unit, Santiago, Chile",
             "Pontificia Univ Catolica, Med, Santiago, Chile",
             "Pontifical Catholic Univ, DUOC Profess Inst, Santiago, Chile",
             "Univ Catolica, Dept Enlace & Med Psicosomat, Santiago",
             "Pontificia Univ Catolica, Fac Quim & Farm, Dept Quim Inorgan, Grp Invest Anal Tratamiento Electroquim Recuperac, Macul",
             "Pontificia Univ Catolica Chie",
             "Pontifica Univ Catorilica Chile",
             "PUC, Programa Doctorado Filosofia, Santiago, Chile",
             "Pontificia Univ Catolica, Fac Med, Psychiat Dept, Santiago",
             "Pontificia Univ Catolica, Fac Med, Pediat Dept, Adolescent Unit, Santiago",
             "Pontificia Univ Catolica, Fac Med, Nutr & Diabet Dept, Santiago",
             "Pontificia Univ Catilica Chile, Inst Sociol, Sociol, Santiago, Chile",
             "Pontificia Univ Catolica, Equipo Cirugia Plast, Santiago, Chile",
             "Pontifical Catholic Univ, Biomed Imaging Ctr, Santiago, Chile",
             "Pontificia Univ Catolica, Dept Struct & Geotech Engn, Santiago, Chile",
             "Pontificia Univ Catolica, Dept Ingn Estruct, Santiago, Chile",
             "Pontificial Catholica Univ Chile",
             "Univ Catolica, Hosp Dr Sotero Rio, Adults Infect Dis Unit, Santiago, Chile",
             "Pontificia Univ Catolica, Fac Ciencias Biol, Dept Genet Mol & Microbiol, Santiago 8331150, Chile",
             "Pontificia Univ Catolica, Natl Excellence Ctr Timber Ind CENAMAD, Santiago",
             "Pontificia Univ Catolica, Dept Ind Engn, Santiago, Chile",
             "Pontificia Univ Catolica, DCC, Escuela Ingn, Vicuna Mackenna 4860, Santiago",
             "Pontificia Univ Catolica, IMFD, Vicuna Mackenna 4860, Santiago",
             "Pontificia Univ Catolica, Inst Ingn Matemat & Computac, Vicuna Mackenna 4860, Santiago",
             "Pontificia Univ Catolica, Fac Hist Geog & Ciencia Polit, Inst Geog, Santiago, Chile",
             "Pontificia Univ Catol, Inst Estudios Urbanos & Territoriales, Santiago, Chile",
             "Pontifical Catholic Univ, Polit Sci Inst, Santiago, Chile",
             "Pontif Univ Catol, Fac Quim & Farm, Dept Quim Inorgan, Ave Vicuna Mackenna 4860, Santiago",
             "Pontificia Univ Catolica, Dept Ecol, Estn Costera Invest Marinas, Santiago, Chile"]
